# Real Estate Clean up

This is a real dataset, and it was downloaded using web scraping techniques. The data contains registers from **Fotocasa** which is one of the most popular real estate websites in Spain. Please, do not do this (web scraping) unless it is for academic purposes.

The dataset was downloaded a few years ago by Henry Navarro, and in no case were economic returns obtained from it.

It contains thousands of data from real houses published on the web www.fotocasa.com. Your goal is to extract as much information as possible with the knowledge you have so far about data science, for example what is the most expensive house in the entire dataset?

Let's start with precisely that question... Good luck!

#### Exercise 00. Read the dataset assets/real_estate.csv and try to visualize the table (★☆☆)

In [33]:
import pandas as pd

# This CSV file contains semicolons instead of comas as separator
df = pd.read_csv('assets/real_estate.csv', sep = ';')
df.T

,0,1,2,3,4,5,6,7,8,9,...,15325,15326,15327,15328,15329,15330,15331,15332,15333,15334
Unnamed: 0,1,2,3,4,5,6,7,8,9,10,...,15326,15327,15328,15329,15330,15331,15332,15333,15334,15335
id_realEstates,153771986,153867863,153430440,152776331,153180188,153934794,153848236,153482331,153885351,153215459,...,153901467,153901401,153901411,153901441,153901392,153901377,150394373,153901397,152607440,153901356
isNew,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
realEstate_name,ferrari 57 inmobiliaria,tecnocasa fuenlabrada ferrocarril,look find boadilla,tecnocasa fuenlabrada ferrocarril,ferrari 57 inmobiliaria,expimad,expimad,expimad,expimad,modesta,...,montehogar 68,nieves,gilmar villalba,servivienda api,pqcentro,infocasa consulting,inmobiliaria pulpon,tecnocasa torrelodones,inmobiliaria pulpon,infocasa consulting
phone_realEstate,912177526.0,916358736.0,916350408.0,916358736.0,912177526.0,912780412.0,912780412.0,912780412.0,912780412.0,NaN,...,911790675.0,NaN,912788041.0,911223996.0,912665783.0,911360461.0,912788039.0,912780348.0,912788039.0,911360461.0
url_inmueble,https://www.fotocasa.es/es/comprar/vivienda/ma...,https://www.fotocasa.es/es/comprar/vivienda/ma...,https://www.fotocasa.es/es/comprar/vivienda/ma...,https://www.fotocasa.es/es/comprar/vivienda/ma...,https://www.fotocasa.es/es/comprar/vivienda/ma...,https://www.fotocasa.es/es/comprar/vivienda/ma...,https://www.fotocasa.es/es/comprar/vivienda/ma...,https://www.fotocasa.es/es/comprar/vivienda/ma...,https://www.fotocasa.es/es/comprar/vivienda/ma...,https://www.fotocasa.es/es/comprar/vivienda/ma...,...,https://www.fotocasa.es/es/comprar/vivienda/ma...,https://www.fotocasa.es/es/comprar/vivienda/ma...,https://www.fotocasa.es/es/comprar/vivienda/ma...,https://www.fotocasa.es/es/comprar/vivienda/ma...,https://www.fotocasa.es/es/comprar/vivienda/ma...,https://www.fotocasa.es/es/comprar/vivienda/ma...,https://www.fotocasa.es/es/comprar/vivienda/ma...,https://www.fotocasa.es/es/comprar/vivienda/ma...,https://www.fotocasa.es/es/comprar/vivienda/ma...,https://www.fotocasa.es/es/comprar/vivienda/ma...
rooms,3.0,3.0,2.0,3.0,2.0,2.0,3.0,2.0,4.0,4.0,...,2.0,3.0,3.0,2.0,2.0,2.0,3.0,4.0,3.0,3.0
bathrooms,2.0,1.0,2.0,1.0,2.0,1.0,2.0,1.0,3.0,2.0,...,2.0,1.0,1.0,1.0,2.0,1.0,1.0,2.0,2.0,2.0
surface,103.0,NaN,99.0,86.0,106.0,70.0,145.0,95.0,277.0,129.0,...,99.0,80.0,85.0,NaN,122.0,96.0,150.0,175.0,101.0,152.0
price,195000,89000,390000,89000,172000,315000,430000,275000,445000,350000,...,215000,184000,150000,229000,264500,259470,165000,495000,195000,765000
date,2019-12-28T18:27:15.9975027Z,2019-12-28T18:27:15.9975027Z,2019-12-28T18:27:15.9975027Z,2019-12-28T18:27:15.9975027Z,2019-12-28T18:27:15.9975027Z,2019-12-28T18:27:15.9680547Z,2019-12-28T18:27:15.9680547Z,2019-12-28T18:27:15.9680547Z,2019-12-28T18:27:15.9680547Z,2019-12-28T13:30:00Z,...,2019-12-17T18:24:00Z,2019-12-17T18:22:00Z,2019-12-17T18:21:00Z,2019-12-17T18:21:00Z,2019-12-17T18:19:00Z,2019-12-17T18:19:00Z,2019-12-17T18:19:00Z,2019-12-17T18:19:00Z,2019-12-17T18:18:00Z,2019-12-17T18:17:00Z
description,Ponemos a la venta piso de 3 dormitorios con t...,"""""Agencia inmobiliaria de FUENLABRADA - zona F...","Lookandfind Boadilla, vende en exclusiva, piso...",Agencia inmobiliaria de FUENLABRADA - zona Fue...,PISOS DE OBRA NUEVA DE 2 Y 3 DORMITORIOS. OBRA...,"Parquerozas, bajo con jardín de diseño, totalm...","Európolis, estupendo ático de 145 m construido...","Parquerozas, estupendo bajo con jardín de 65 m...","Las Rozas, Punta Galea, precioso chalet adosad...",Excelente piso de 4 habitaciones.\nVivienda to...,...,Extupendo ATICO y magnificas viviendas muy am...,"Se vende bonito piso de 75m en Aluche, está co...",Gilmar Villalba vende dúplex con jardín para r...,OPORTUNIDAD EN MALASAÑA !!!!!!\r\n\r\nVivienda...,ENTREGA INMEDIATA - ULTIMAS VIVIENDAS DISPONIB...,¡¡¡IDEAL PROFESIONALES E INVERSORES¡¡¡ \nINFOC...,"Planta baja con cocinas, una de ellos posibili...",NaN,"Piso de 3 dormitorios con armarios empotrados,...",INFOCASA vende este bonito piso reformado con ...
address,"Calle Presidente Felipe Gonzalez, Arganda del Rey","Calle Polvoranca, 6, Fuenlabrada","Calle Reyes Católicos, Boadilla del Monte","Barrio San Andres, Fuenlabrada",Arganda del Rey,Las Rozas de Madrid,Las Rozas de Madrid,Las Rozas de Madrid,Las Rozas de Madrid,Madrid Capital,...,"Calle de Luis Sauquillo, 77, Fuenlabrada",Madrid Capital,El Escorial,"Calle de Manuela Malasaña, Madrid Capital","Calle Luis Carrillo de Toledo, 3, Pinto",Madrid Capital,Velilla de San Antonio,Torrelodones,Velilla de San Antonio,"Paseo de la Castellana, Madrid Capital"
country,España,España,España,España,España,España,España,España,España,España,...,España,España,España,España,España,España,España,España,España,España
level1,Madrid,Madrid,Madrid,Madrid,Madrid,Madrid,Madrid,Madrid,Madrid,Madrid,...,Madrid,Madrid,Madrid,Madrid,Madrid,Madrid,Madrid,Madrid,Madrid,Madrid
level2,Madrid,Madrid,Madrid,Madrid,Madrid,Madrid,Madrid,Madrid,Madrid,Madrid,...,Madrid,Madrid,Madrid,Madrid,Madrid,Madrid,Madrid,Madrid,Madrid,Madrid
level3,Madrid Sureste - Cuenca Tajuña,Zona Sur de Madrid,Zona Noroeste,Zona Sur de Madrid,Madrid Sureste - Cuenca Tajuña,Zona Noroeste,Zona Noroeste,Zona Noroeste,Zona Noroeste,"Madrid, Zona de",...,Zona Sur de Madrid,"Madrid, Zona de",Zona Noroeste,"Madrid, Zona de",Zona Sur de Madrid,"Madrid, Zona de",Madrid Sureste - Cuenca Tajuña,Zona Noroeste,Madrid Sureste - Cuenca Tajuña,"Madrid, Zona de"
level4,"Arganda del Rey, Zona de","Fuenlabrada, Zona de","Boadilla del Monte, Zona de","Fuenlabrada, Zona de","Arganda del Rey, Zona de","Las Rozas de Madrid, Zona de","Las Rozas de Madrid, Zona de","Las Rozas de Madrid, Zona de","Las Rozas de Madrid, Zona de",NaN,...,"Fuenlabrada, Zona de",NaN,"El Escorial, Zona de",NaN,"Pinto, Zona de",NaN,"Velilla de San Antonio, Zona de","Torrelodones, Zona de","Velilla de San Antonio, Zona de",NaN
level5,Arganda del Rey,Fuenlabrada,Boadilla del Monte,Fuenlabrada,Arganda del Rey,Las Rozas de Madrid,Las Rozas de Madrid,Las Rozas de Madrid,Las Rozas de Madrid,Madrid Capital,...,Fuenlabrada,Madrid Capital,El Escorial,Madrid Capital,Pinto,Madrid Capital,Velilla de San Antonio,Torrelodones,Velilla de San Antonio,Madrid Capital
level6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
level7,Perlita,Centro,Sector B,Centro,Centro,El Pinar - Punta Galea,Europolis,El Pinar - Punta Galea,El Pinar - Punta Galea,Carabanchel,...,El Arroyo - La Fuente,Latina,Navalquejigo - Los Arroyos,Centro,San José - Buenos Aires,Tetuán,NaN,Casco Antiguo,NaN,Tetuán
level8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Puerta bonita,...,NaN,Águilas,NaN,Universidad - Malasaña,NaN,Berruguete,NaN,NaN,NaN,Castillejos - Cuzco
upperLevel,Perlita,Centro,Sector B,Centro,Centro,El Pinar - Punta Galea,Europolis,El Pinar - Punta Galea,El Pinar - Punta Galea,Puerta bonita,...,El Arroyo - La Fuente,Águilas,Navalquejigo - Los Arroyos,Universidad - Malasaña,San José - Buenos Aires,Berruguete,Velilla de San Antonio,Casco Antiguo,Velilla de San Antonio,Castillejos - Cuzco
countryId,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
level1Id,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
level2Id,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
level3Id,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
level4Id,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
level5Id,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
level6Id,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
level7Id,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
level8Id,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
accuracy,0,1,0,0,0,0,0,0,0,0,...,1,0,0,0,1,0,0,0,0,0
latitude,"40,2948276786438","40,28674","40,4115646786438","40,2853785786438","40,2998774864376","40,53391","40,5105842135624","40,53294","40,5363057864376","40,37502",...,"40,28062","40,3798763","40,60074","40,42844","40,24007","40,45416","40,36652","40,57444","40,36967","40,45773"
longitude,"-3,44402412135624","-3,79351","-3,90662252135624","-3,79508142135624","-3,45226301356237","-3,89445","-3,89436578643763","-3,89898","-3,89294421356237","-3,74391",...,"-3,79869","-3,7714352","-4,06255","-3,70414","-3,70606","-3,70286","-3,48951","-3,92124","-3,48105","-3,69068"
zipCode,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
customZone,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

#### Exercise 01. Which is the most expensive house in the dataset? (★☆☆)

Print the address and the price of the selected house. For example:

`The house with address General Street Nº5 is the most expensive and its price is 5000000 USD`

In [34]:
print(max(df['price'])) # most expensive house value looks good 
print(min(df['price'])) # least expensive house value can't be zero --> column needs cleanup

8500000
0

In [35]:
# TODO
df.sort_values(by='price', axis=0, ascending=False, inplace=True)
expensive_house_address = df.iloc[0]['address']
expensive_house_price = df.iloc[0]['price']
print(f"The house with address {expensive_house_address} is the most expensive and its price {expensive_house_price} USD")

The house with address El Escorial is the most expensive and its price 8500000 USD

#### Exercise 02. Which is the cheapest house in the dataset? (★☆☆)

Print the address and the price of the selected house. For example:

`The house with address Concrete Street Nº1 is the cheapest and its price is 12000 USD`

In [36]:
# TODO
df.sort_values(by='price', axis=0, ascending=False, inplace=True)
cheapest_house_address = df.iloc[-1]['address']
cheapest_house_price = df.iloc[-1]['price']

print(f"The house with address {cheapest_house_address} is the cheapest and its price {cheapest_house_price} USD")

The house with address Parla is the cheapest and its price 0 USD

In [37]:
# cheapest house can't be zero, finding the real cheapest house 
df.sort_values(by='price', axis=0, ascending=True, inplace=True)
real_cheapest_house_price = df[df['price'] != 0].iloc[0]['price']
real_cheapest_house_address = df[df['price'] != 0].iloc[0]['address']
print(f"The house with address {real_cheapest_house_address} is the cheapest and its price {real_cheapest_house_price} USD")

The house with address Berlin, Coslada is the cheapest and its price 600 USD

#### Exercise 03. Which is the biggest and the smallest house in the dataset? (★☆☆)

Print both the address and the surface of the selected houses. For example:

`The biggest house is located on Yukka Street Nº10 and its surface is 5000 meters`

`The smallest house is located on County Road 1 N and its surface is 200 meters`

In [38]:
# TODO
df = pd.read_csv('assets/real_estate.csv', sep = ';')
df['surface'].unique()

# data has NaN value in one of the rows, 'surface' column needs clean up

array([1.0300e+02,        nan, 9.9000e+01, 8.6000e+01, 1.0600e+02,
       7.0000e+01, 1.4500e+02, 9.5000e+01, 2.7700e+02, 1.2900e+02,
       2.4600e+02, 6.7000e+01, 5.0000e+01, 2.7000e+02, 7.3000e+01,
       1.0100e+02, 3.2000e+02, 1.5000e+02, 1.1000e+02, 1.4400e+02,
       2.5300e+02, 4.5000e+01, 3.0000e+02, 9.1000e+01, 6.6000e+01,
       1.6000e+02, 1.2500e+02, 1.4000e+02, 3.8000e+02, 3.0300e+02,
       3.8300e+02, 2.3200e+02, 8.5000e+01, 4.4800e+02, 9.0000e+02,
       3.4000e+02, 6.5000e+01, 6.2000e+01, 8.9000e+01, 1.2200e+02,
       1.4800e+02, 6.9000e+01, 9.8000e+01, 2.0500e+02, 2.0400e+02,
       6.8000e+01, 1.5900e+02, 5.9000e+01, 2.0200e+02, 9.2000e+01,
       4.6000e+01, 6.1000e+01, 1.9800e+02, 8.3000e+01, 3.8000e+01,
       4.7000e+01, 5.3000e+01, 3.9000e+01, 1.2700e+02, 1.3200e+02,
       1.3400e+02, 9.6000e+01, 5.4000e+01, 8.1000e+01, 1.2300e+02,
       1.0500e+02, 9.7000e+01, 3.5000e+01, 4.4000e+01, 3.7000e+01,
       5.8000e+01, 1.2800e+02, 1.0000e+02, 7.5000e+01, 8.8000e+01,
       5.2000e+01, 8.7000e+01, 9.0000e+01, 1.6800e+02, 1.6100e+02,
       2.5000e+02, 7.9000e+01, 7.6000e+01, 5.6000e+01, 1.2000e+02,
       2.4800e+02, 4.1000e+01, 3.2000e+01, 5.5000e+01, 4.0000e+02,
       1.0900e+02, 9.3000e+01, 1.3700e+02, 4.5000e+02, 7.0000e+02,
       1.4200e+02, 1.3300e+02, 5.1000e+01, 1.3500e+02, 2.3500e+02,
       2.9200e+02, 1.4700e+02, 1.3100e+02, 1.1200e+02, 6.3000e+01,
       1.0400e+02, 1.0700e+02, 1.4600e+02, 6.4000e+01, 1.5200e+02,
       8.0000e+01, 7.7000e+01, 7.2000e+01, 2.7200e+02, 4.1200e+02,
       1.2600e+02, 2.2100e+02, 2.2000e+02, 1.4300e+02, 1.9500e+02,
       2.4000e+02, 1.8700e+02, 4.3000e+01, 7.4000e+01, 2.0100e+02,
       6.0000e+01, 3.8400e+02, 4.2000e+01, 4.0000e+01, 2.8700e+02,
       4.6700e+02, 1.9300e+02, 1.7000e+02, 8.2000e+01, 1.1400e+02,
       1.5600e+02, 2.9300e+02, 2.3000e+02, 1.8000e+02, 1.7500e+02,
       2.6500e+02, 7.8000e+01, 7.5000e+02, 1.6400e+02, 2.4700e+02,
       3.6600e+02, 3.9800e+02, 1.4000e+03, 4.4500e+02, 3.1300e+02,
       1.2100e+02, 2.9400e+02, 2.0900e+02, 4.6300e+02, 1.3600e+02,
       4.5400e+02, 6.3500e+02, 2.6000e+02, 1.7600e+02, 3.4500e+02,
       4.1300e+02, 1.1300e+02, 4.4000e+02, 1.3800e+02, 2.5100e+02,
       3.6300e+02, 5.4100e+02, 1.5800e+02, 3.7000e+02, 6.2000e+02,
       2.0000e+02, 2.1900e+02, 1.1900e+02, 1.0800e+02, 2.8000e+02,
       2.9700e+02, 2.4900e+02, 2.1400e+02, 4.9000e+01, 1.5400e+02,
       2.1800e+02, 5.0000e+02, 2.2500e+02, 1.8200e+02, 1.0200e+02,
       2.6200e+02, 1.8500e+02, 2.4300e+02, 1.1500e+02, 8.0000e+02,
       9.4000e+01, 6.0700e+02, 3.4300e+02, 2.4000e+03, 5.7500e+02,
       3.5000e+02, 8.4000e+01, 1.1700e+02, 2.2200e+02, 4.3200e+02,
       5.9500e+02, 1.4900e+02, 5.7000e+02, 1.2400e+02, 3.5600e+02,
       2.0800e+02, 7.8300e+02, 4.1500e+02, 7.4100e+02, 1.6200e+02,
       4.4900e+02, 4.3000e+02, 3.3000e+01, 2.7000e+01, 2.7100e+02,
       1.1800e+02, 1.5000e+01, 1.1100e+02, 2.6000e+01, 3.0500e+02,
       2.6700e+02, 1.5300e+02, 2.3700e+02, 2.6600e+02, 1.6500e+02,
       4.2600e+02, 4.8000e+01, 3.7400e+02, 5.5200e+02, 2.1000e+02,
       2.1500e+02, 6.7000e+02, 7.3500e+02, 2.2800e+02, 3.3200e+02,
       2.4400e+02, 5.4300e+02, 3.4900e+02, 4.6200e+02, 3.7800e+02,
       3.7500e+02, 7.2500e+02, 4.0200e+02, 4.3300e+02, 1.4100e+02,
       3.9400e+02, 3.2700e+02, 2.5700e+02, 1.7200e+02, 1.9000e+02,
       4.0300e+02, 1.8100e+02, 5.7000e+01, 4.0100e+02, 3.1700e+02,
       9.3400e+02, 2.7800e+02, 4.8500e+02, 1.7300e+02, 3.4800e+02,
       3.3000e+02, 1.5500e+02, 2.2900e+02, 1.3900e+02, 2.5400e+02,
       4.8200e+02, 2.2400e+02, 4.9900e+02, 5.2500e+02, 1.3000e+02,
       1.5000e+03, 1.7800e+02, 2.0300e+02, 5.5400e+02, 2.5900e+02,
       3.6900e+02, 6.9600e+02, 5.5000e+02, 3.3900e+02, 3.1000e+02,
       2.9000e+02, 6.3000e+02, 1.7900e+02, 3.6000e+01, 7.1000e+01,
       5.8000e+02, 6.0000e+02, 3.6000e+02, 2.8500e+02, 4.9100e+02,
       5.6700e+02, 1.9200e+02, 4.0800e+02, 5.2100e+02, 5.0700e+02,
       6.0400e+02, 7.7500e+02, 4.9000e+02, 2.0000e+03, 3.1500e+02,
       1.1800e+03, 1.6300e+02, 7.0100e+02, 1.2000e+03, 2.3400e+02,
       3.5800e+02, 2.4100e+02, 4.8800e+02, 9.0400e+02, 7.8200e+02,
       2.5600e+02, 8.2900e+02, 9.1800e+02, 4.4300e+02, 2.6300e+02,
       7.4000e+02, 3.9000e+02, 2.1600e+02, 5.0830e+03, 8.2400e+02,
       4.6000e+02, 6.4700e+02, 3.2600e+02, 8.5000e+02, 3.6400e+02,
       2.3100e+02, 2.3600e+02, 1.1600e+02, 2.3800e+02, 4.3900e+02,
       2.9900e+02, 2.4200e+02, 2.7500e+02, 1.0000e+03, 2.5500e+02,
       2.3300e+02, 2.2600e+02, 7.7100e+02, 4.7600e+02, 5.3200e+02,
       1.9900e+02, 3.7900e+02, 1.8400e+02, 2.2700e+02, 1.8300e+02,
       2.8100e+02, 3.3500e+02, 1.6700e+02, 1.6600e+02, 3.2300e+02,
       3.1600e+02, 3.1100e+02, 2.1100e+02, 5.9400e+02, 2.9600e+02,
       1.0900e+03, 6.8000e+02, 9.8500e+02, 1.6900e+02, 7.5500e+02,
       1.0160e+03, 3.3600e+02, 1.8800e+02, 2.7300e+02, 3.2500e+02,
       5.3600e+02, 3.1800e+02, 4.7400e+02, 1.7100e+02, 2.1200e+02,
       2.0600e+02, 3.3400e+02, 1.5700e+02, 3.6500e+02, 2.0700e+02,
       1.9700e+02, 3.6800e+02, 5.9700e+02, 5.6600e+02, 3.4100e+02,
       3.1400e+02, 2.7400e+02, 2.4500e+02, 2.6400e+02, 1.8600e+02,
       2.1000e+01, 4.4200e+02, 3.5100e+02, 3.2900e+02, 2.2300e+02,
       2.6800e+02, 1.7940e+03, 3.4000e+01, 3.0200e+02, 7.0500e+02,
       3.5300e+02, 2.7900e+02, 4.1900e+02, 2.5200e+02, 1.7400e+02,
       1.7700e+02, 4.1400e+02, 3.2200e+02, 2.7600e+02, 2.6100e+02,
       2.9500e+02, 2.3900e+02, 2.8400e+02, 8.1000e+02, 1.9100e+02,
       1.9400e+02, 2.5000e+01, 4.5200e+02, 2.8300e+02, 2.6900e+02,
       6.5000e+02, 8.3500e+02, 3.9900e+02, 3.4400e+02, 4.3100e+02,
       4.2500e+02, 5.2000e+02, 2.9800e+02, 4.6500e+02, 5.0900e+02,
       4.7500e+02, 3.8700e+02, 4.5500e+02, 8.0500e+02, 3.0100e+02,
       3.9600e+02, 4.8000e+02, 7.8500e+02, 4.8400e+02, 3.8200e+02,
       2.8600e+02, 1.5970e+03, 7.8400e+02, 1.2900e+03, 3.5200e+02,
       9.5400e+02, 8.3200e+02, 5.1000e+02, 3.9700e+02, 4.6400e+02,
       5.1200e+02, 9.8600e+02, 6.6800e+02, 2.8200e+02, 6.0800e+02,
       3.9500e+02, 6.6900e+02, 1.9600e+02, 2.0500e+03, 2.1300e+02,
       4.1000e+02, 3.4200e+02, 4.4700e+02, 3.7300e+02, 4.7800e+02,
       3.0700e+02, 2.9100e+02, 3.3300e+02, 4.5700e+02, 4.8900e+02,
       5.0300e+02, 4.7100e+02, 2.8800e+02, 7.7000e+02, 3.0600e+02,
       7.0600e+02, 1.5100e+02, 3.5700e+02, 2.1700e+02, 6.1300e+02,
       3.7100e+02, 5.7400e+02, 3.0800e+02, 1.8900e+02, 2.9000e+01,
       4.2300e+02, 3.9100e+02, 3.7700e+02, 7.3000e+02, 4.9800e+02,
       5.9300e+02, 4.7000e+02, 4.1700e+02, 8.4000e+02, 6.5500e+02,
       5.7800e+02, 5.0500e+02, 5.7300e+02, 3.6700e+02, 3.0400e+02,
       4.8600e+02, 1.4980e+03, 1.0500e+03, 4.2800e+02, 8.7000e+02,
       1.2290e+03, 5.6400e+02, 3.7200e+02, 6.1500e+02, 7.1400e+02,
       4.2000e+02, 3.2100e+02, 3.5500e+02, 3.5400e+02, 5.6800e+02,
       3.4700e+02, 3.2400e+02, 3.1000e+01, 4.0900e+02, 4.4400e+02,
       9.9000e+02, 3.1200e+02, 7.3800e+02, 8.3100e+02, 4.1100e+02,
       8.2800e+02, 3.8500e+02, 6.2600e+02, 6.1800e+02, 5.0600e+02,
       5.8300e+02, 4.7700e+02, 3.0000e+01, 3.9300e+02, 3.9200e+02,
       6.3200e+02, 4.9600e+02, 4.5900e+02, 5.5900e+02, 6.0100e+02,
       7.2000e+02, 8.2300e+02, 3.0900e+02, 2.5800e+02, 6.4100e+02,
       3.1900e+02, 4.4100e+02, 7.2200e+02, 4.2700e+02, 7.8600e+02,
       5.8800e+02, 1.2780e+03, 7.4300e+02, 5.8900e+02, 6.1000e+02,
       5.4400e+02, 3.4600e+02, 4.2900e+02, 7.2400e+02, 5.2900e+02,
       5.6000e+02, 5.9000e+02, 6.9000e+02, 6.4300e+02, 2.0660e+03,
       5.2700e+02, 7.8800e+02, 4.8100e+02, 7.6000e+02, 8.2000e+02,
       2.4900e+05, 4.2200e+02, 6.1100e+02, 4.3500e+02, 4.0600e+02,
       5.3000e+02, 6.4000e+02, 1.5450e+03, 2.5800e+03, 4.1600e+02,
       8.3000e+02, 1.3200e+03, 1.2450e+03, 3.2800e+02, 4.3800e+02,
       3.3700e+02, 5.9200e+02, 3.3800e+02, 5.3100e+02, 6.6100e+02,
       1.3500e+03, 1.0790e+03, 6.1900e+02, 3.7600e+02, 4.5300e+02,
       5.4700e+02, 3.8800e+02, 7.4200e+02, 7.5600e+02, 8.7800e+02,
       8.6000e+02, 8.9500e+02, 6.9200e+02, 1.2500e+03, 1.1650e+03,
       1.4780e+03, 6.3700e+02, 8.4800e+02, 8.9400e+02, 5.3300e+02,
       2.8900e+02, 5.1100e+02, 6.3400e+02, 5.9600e+02, 5.4000e+02,
       1.4700e+03, 7.0200e+02, 6.6300e+02, 6.5300e+02, 6.9500e+02,
       1.3740e+03, 7.3600e+02, 6.5100e+02, 9.9100e+02, 3.6200e+02,
       6.2200e+02, 5.1500e+02, 1.1840e+03, 1.0410e+03, 7.8000e+02,
       4.2400e+02, 8.4500e+02, 6.2100e+02, 4.7300e+02, 2.6000e+03,
       5.5700e+02, 7.3700e+02, 5.5040e+03, 2.4000e+01, 6.7600e+02,
       1.1000e+03, 3.8600e+02, 6.2700e+02, 1.2670e+03, 4.4600e+02,
       8.7600e+02, 5.5600e+02, 1.1500e+03, 9.9200e+02, 1.4500e+03,
       5.5800e+02, 3.8100e+02, 1.0200e+03, 1.3380e+03, 6.5200e+02,
       4.7900e+02, 2.3000e+01, 6.8200e+02, 6.4200e+02, 7.7400e+02,
       4.0500e+02, 4.6600e+02, 3.5900e+02, 6.1700e+02, 3.3100e+02,
       6.6600e+02, 1.1240e+03, 2.2000e+01, 1.2920e+03, 4.8300e+02,
       1.0800e+03, 4.3600e+02, 1.9700e+03, 7.1200e+02, 6.4800e+02,
       1.3000e+03, 4.3700e+02, 4.9200e+02, 5.6200e+02, 8.7500e+02,
       9.0100e+02, 4.0700e+02, 6.1600e+02, 7.7300e+02, 7.1500e+02,
       4.5600e+02, 7.1000e+02, 1.6000e+03, 1.2360e+03, 1.7000e+03,
       1.1270e+03, 1.5870e+03, 4.0400e+02, 8.5200e+02, 4.5000e+03,
       7.9900e+02, 5.2400e+02, 7.6900e+02, 9.1000e+02, 7.1900e+02,
       6.6666e+04, 8.0400e+02, 5.0200e+02, 5.6100e+02, 9.9600e+02,
       6.1200e+02, 7.3200e+02, 1.9250e+03, 1.7500e+03, 1.6150e+03,
       9.5000e+02, 5.8100e+02, 9.2500e+02, 5.6500e+02, 5.3900e+02,
       9.7500e+02, 7.3300e+02, 5.3800e+02, 5.4800e+02, 1.8000e+01,
       7.6200e+02, 4.6800e+02, 7.6100e+02, 6.9700e+02, 7.8900e+02,
       6.7500e+02, 1.9310e+03, 9.2000e+02, 5.0400e+02, 1.6853e+04,
       8.3600e+02, 5.7700e+02, 3.9000e+03, 1.4990e+03])

In [39]:
# sorting the data frame based on the surface area 
df.sort_values(by='surface', axis=0, ascending=False, inplace=True) # sort 'surface' column from max to min 

# Accessing the address & surface area values of the biggest house in the data frame 
biggest_house_address = df.iloc[0]['address']
biggest_house_area = df.iloc[0]['surface']
print(f"The biggest house is located on {biggest_house_address} and its surface is {biggest_house_area} meters")

# Accessing the address & surface area values of the smallest house in the data frame 
smallest_house_address = df[df['surface'].notna()].iloc[-1]['address']
smallest_house_area = df[df['surface'].notna()].iloc[-1]['surface']
print(f"The smallest house is located on {smallest_house_address} and its surface is {smallest_house_area} meters")

The biggest house is located on Sevilla la Nueva and its surface is 249000.0 meters
The smallest house is located on Calle Amparo,  Madrid Capital and its surface is 15.0 meters

#### Exercise 04. How many populations (level5 column) the dataset contains? (★☆☆)

Print the names of the populations with a comma as a separator. For example:

`> print(populations)`

`population1, population2, population3, ...`

In [40]:
# TODO

#### Exercise 05. Does the dataset contain NAs? (★☆☆)

Print a boolean value (`True` or `False`) followed by the rows/cols that contains NAs.

In [41]:
# TODO

#### Exercise 06. Delete the NAs of the dataset, if applicable (★★☆)

Print a comparison between the dimensions of the original DataFrame versus the DataFrame after the deletions.

In [42]:
# TODO

#### Exercise 07. Which is the mean of prices in the population (level5 column) of "Arroyomolinos (Madrid)"? (★★☆)

Print the obtained value.

In [43]:
# TODO

#### Exercise 08. Plot the histogram of prices for the population (level5 column) of "Arroyomolinos (Madrid)" and explain what you observe (★★☆)

Print the histogram of the prices and write in the Markdown cell a brief analysis about the plot.

In [44]:
# TODO: Code

**TODO: Markdown**. To write here, double-click on this cell, remove this content and place the text you want to write. Then, execute the cell.

#### Exercise 09. Are the average prices of "Valdemorillo" and "Galapagar" the same? (★★☆)

Print both average prices and then write a conclusion about them.

In [45]:
# TODO

#### Exercise 10. Are the average prices per square meter (price/m2) of "Valdemorillo" and "Galapagar" the same? (★★☆)

Print both average prices and then write a conclusion about it.

Hint: Create a new column called `pps` (price per square meter) and then analyze the values.

In [46]:
# TODO

#### Exercise 11. Analyze the relation between the surface and the price of the houses (★★☆)

Hint: You can make a `scatter plot`, then write a conclusion about it.

In [47]:
# TODO: Code

**TODO: Markdown**. To write here, double-click on this cell, remove this content and place the text you want to write. Then, execute the cell.

#### Exercise 12. How many real estate agencies does the dataset contain? (★★☆)

Print the obtained value.

In [48]:
# TODO

#### Exercise 13. Which is the population (level5 column) that contains the most houses? (★★☆)

Print both the population and the number of houses.

In [49]:
# TODO

#### Exercise 14. Now let's work with the "south belt" of Madrid. Make a subset of the original DataFrame that contains the following populations (level5 column): "Fuenlabrada", "Leganés", "Getafe", "Alcorcón" (★★☆)

Hint: Filter the original DataFrame using the column `level5` and the function `isin`.

In [50]:
# TODO

#### Exercise 15. Make a bar plot of the median of the prices and explain what you observe (you must use the subset obtained in Exercise 14) (★★★)

Print the bar of the median of the prices and write in the Markdown cell a brief analysis about the plot.

In [51]:
# TODO: Code

**TODO: Markdown**. To write here, double-click on this cell, remove this content and place the text you want to write. Then, execute the cell.

#### Exercise 16. Calculate the sample mean and variance of the variables: price, rooms, surface area and bathrooms (you must use the subset obtained in Exercise 14) (★★★)

Print both values for each variable.

In [52]:
# TODO

#### Exercise 17. What is the most expensive house in each population? You must use the subset obtained in Exercise 14 (★★☆)

Print both the address and the price of the selected house of each population. You can print a DataFrame or a single line for each population.

In [53]:
# TODO

#### Exercise 18. Normalize the variable of prices for each population and plot the 4 histograms in the same plot (you must use the subset obtained in Exercise 14) (★★★)

For the normalization method, you can use the one you consider; there is not a single correct answer to this question. Print the plot and write in the Markdown cell a brief analysis about the plot.

Hint: You can help yourself by reviewing the *multihist* demo of Matplotlib.

In [54]:
# TODO

**TODO: Markdown**. To write here, double-click on this cell, remove this content and place the text you want to write. Then, execute the cell.

#### Exercise 19. What can you say about the price per square meter (price/m2) between the towns of "Getafe" and "Alcorcón"? You must use the subset obtained in Exercise 14 (★★☆)

Hint: Create a new column called `pps` (price per square meter) and then analyze the values.

In [55]:
# TODO

#### Exercise 20. Make the same plot for 4 different populations (level5 column) and rearrange them on the same graph. You must use the subset obtained in Exercise 14 (★★☆)
 
Hint: Make a scatter plot of each population using subplots.

In [56]:
# TODO

#### Exercise 21. Make a plot of the coordinates (latitude and longitude columns) of the south belt of Madrid by color of each population (you must use the subset obtained in Exercise 14) (★★★★)

Execute the following cell, and then start coding in the next one. You must implement a simple code that transforms the coordinates columns in a Python dictionary (add more information if needed) and then add it to the map

In [57]:
from ipyleaflet import Map, basemaps

# Map centered on (60 degrees latitude and -2.2 degrees longitude)
# Latitude, longitude
map = Map(center = (60, -2.2), zoom = 2, min_zoom = 1, max_zoom = 20, 
    basemap=basemaps.Stamen.Terrain)
map

AttributeError: Stamen

In [ ]:
## HERE: plot the coordinates of the estates

## PUT HERE YOUR CODE: